### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by DeepOceanBird** [pourer/pika_exporter#1]
1、编译后，pika_exporter 程序名称变成了：pika_expoter。
2、metrics 中缺少参数：is_slots_reloading、pika_kv_keys。
希望可以修复一下，谢谢。

**Comment by DeepOceanBird** [comment]
补充说明：
1、监控 pika3.0.4 时，metrics 中缺少 pika_kv_keys、is_slots_reloading 参数的值。
2、监控 pika3.0.6 以上版本时，由于 into keyspace 内容格式改变，导致 metrics 中没有  pika_kv_keys、pika_hash_keys、pika_list_keys、pika_set_keys、pika_zset_keys 等参数的值。

**Comment by pourer** [comment]
1、编译后程序名称变成：pika_expoter
是由于makefile中写错了，fixed
![image](https://user-images.githubusercontent.com/5706696/63830590-1a50d980-c99f-11e9-9162-f7bff98dfc3b.png)

2、metrics信息可以通过metrics_file进行配置对应INFO中的key信息，目前pika_exporter使用的是
[default_pika_metrics_file.ini](https://raw.githubusercontent.com/pourer/pika_exporter/master/contrib/default_pika_metrics_file.ini)中定义的metrics信息

> 在启动pika_exporter时可通过命令行参数`--metrics-file`指定metrics_file

详细信息参考：[INFO Metrics Definition](https://github.com/pourer/pika_exporter#info-metrics-definition)

但是，如果要添加的metrics是类似于is_bgsaving这种复杂格式的INFO-Key，并且想要对复杂格式进行拆分展示，则此时需要修改pika_exporter代码，如果出现这种需求场景欢迎继续提issue，我会及时跟进
