### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by WPFS** [pourer/pika_exporter#3]
警告日志
{"level":"warning","msg":"convert value to float64 failed. addr:10.111.219.134:60500 metricName:binlog_offset valueName:binlog_offset_value value:","time":"2019-12-09T16:45:33+08:00"}

CentOS7.7系统  pika版本3.2.7  go1.13.3
运行命令:
/usr/bin/pika_exporter -web.listen-address 10.111.219.134:10000--pika.addr 10.111.219.134:60500

现象:
 grafana base info不出图

**Comment by pourer** [comment]
Pika从3.1.0版本开始支持了多库模式，Info信息中有部分信息与之前产生变化，导致解析出错。随后会对pika_exporter进行修改以支持Pika多库版本的Info信息

**Comment by pourer** [comment]
@WPFS 最新的pika exporter已经支持pika全版本的监控指标采集
