### ISSUE TITLE
Buiding 写错了。exporter少了个r

### ISSUE THREAD

**Issue by handsoncheng** [pourer/pika_exporter#4]
$ go get github.com/pourer/pika_expoter
$ cd $GOPATH/src/github.com/pourer/pika_expoter
$ make
$ ./bin/pika_exporter <flags>

**Comment by pourer** [comment]
已修改，多谢指正

**Comment by handsoncheng** [comment]
还有几个都是pika_expoter，麻烦修改下哈

**Comment by pourer** [comment]
最新的版本已经修复了这些问题
