### ISSUE TITLE
can not running 

### ISSUE THREAD

**Issue by qiuwenhuifx** [pourer/pika_exporter#6]
[1] 44146
INFO[0000] Pika Metrics Exporter  master build date: 2020-07-22 13:30:24 +07 sha: 8824c76 go version: go1.14.6 linux/amd64 
{"level":"info","msg":"stats KeySpace not open","time":"2020-07-22T13:34:10+07:00"}
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "pika_binlog_offset_filenum", help: "pika serve instance binlog file num for each db", constLabels: {}, variableLabels: [addr alias db]}

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000140a00, 0xc0001cdda8, 0x1, 0x1)
        /root/pika_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:401 +0xad
main.main()
        /root/pika_exporter/main.go:94 +0x6ff
[1]+  Exit 2                  ./pika_exporter --pika.addr 127.0.0.1:35000 2>&1

**Comment by qiuwenhuifx** [comment]
-----------Pika server 2.2.6 ----------

**Comment by pourer** [comment]
The latest version has solved the problem. Please use [release v0.2.0](https://github.com/pourer/pika_exporter/releases/tag/v0.2.0)
