### ISSUE TITLE
pika 3.0.10 版本无keyspace相关统计信息

### ISSUE THREAD

**Issue by enjoychaim** [pourer/pika_exporter#7]
![image](https://user-images.githubusercontent.com/12760278/105824550-776c1700-5ff9-11eb-9417-bc1024dd26b6.png)

怎么操作才可以获取到keyspace的统计信息呢?

**Comment by pourer** [comment]
项目中的grafana_prometheus_pika_dashboard.json比较老了，由于Pika各版本之间存在的INFO差异，因此暂时较难制作统一的grafana_prometheus_pika_dashboard.json

在实际使用时，有些dashboard需要修改Query Metrics中的指标名称以及指标labels才可以正常显示
具体的指标名称以及指标labels参见[README INFO Metrics Definition](https://github.com/pourer/pika_exporter/blob/master/README.md#info-metrics-definition)

另外需要注意：
> 对于Pika来说，需要执行 `info keyspace 1` 才会对key数量进行统计

- 可以通过工具连接Pika然后手动执行 `info keyspace 1` 
- 也可以在启动pika_exporter时，配置向Pika定时执行 `info keyspace 1` 的命令行参数，如果key的数据量较大，建议尽量设置为业务低峰的小时点

![image](https://user-images.githubusercontent.com/5706696/105944198-cbc8d280-609d-11eb-9ab9-196a700a1db3.png)
